### ISSUE TITLE
String processing in numexpr

### ISSUE THREAD

**Issue by mpage38** [pydata/numexpr#233]
I find the bcolz/numexpr combination very powerful. I sometimes process strings in huge bcolz ctables and I dream of numexpr supporting string operations such as concatenation, left, split, ... as efficiently as for numerical and Boolean data. For example, Iworked some time ago on the Avito Context Ad click competition on Kaggle https://www.kaggle.com/c/avito-context-ad-clicks/data and I was unable to efficiently process  the `Params ` attribute in `AdsInfo` table, or `SearchQuery `and `SearchParams `in `SearchInfo ` table.

**Comment by gdementen** [comment]
Well, I guess several persons would find this useful, but so far nobody stepped up to implement it. I guess that if you did a pull request implementing this, it would probably be accepted... You may want to look at #135 for some inspiration, but what you ask would be significantly more difficult because you need to create (ie allocate) new strings, which no op currently does.

**Comment by robbmcleod** [comment]
Closing as the issue appears to be stale.
