### ISSUE TITLE
abs(x) ~3x slower than explicit calculation? 

### ISSUE THREAD

**Issue by itdaniher** [pydata/numexpr#249]
```
In [11]: b = np.random.rand(500, 500) + 1j * np.random.rand(500, 500)

In [12]: %timeit ne.evaluate('abs(b)')
10 loops, best of 3: 49.4 ms per loop

In [13]: %timeit ne.evaluate('(b.real**2 + b.imag**2)**0.5')
10 loops, best of 3: 16.8 ms per loop

In [14]: np.allclose(ne.evaluate('(b.real**2 + b.imag**2)**0.5') ,ne.evaluate('abs(b)'))
Out[14]: True
```

`b` is `complex128` here.

Interestingly, this doesn't hold true for `complex64`.

```
In [18]: b = b.astype('complex64')

In [19]: %timeit ne.evaluate('(b.real**2 + b.imag**2)**0.5')
10 loops, best of 3: 24.3 ms per loop

In [20]: %timeit ne.evaluate('abs(b)')
100 loops, best of 3: 14.9 ms per loop
```

Platform specific info:

```
numexpr=2.6.2
Linux debian 4.10.0-sun8i #3 SMP Thu Feb 23 19:57:03 CET 2017 armv7l armv7l armv7l GNU/Linux
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux

model name      : ARMv7 Processor rev 5 (v7l)
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm

```

**Comment by robbmcleod** [comment]
Do you start the interpreter with some junk call before you do your tests?  That can help make the result more interpretable.  Try also changing the order of your tests?

NumExpr 2.6 doesn't support `complex64` so your second result doesn't make a lot of sense.  What is the `dtype` in those two cases?  Presumably it's upcast.

Note that there is an alpha branch of version 3.0 available: [https://github.com/pydata/numexpr/tree/numexpr-3.0](url)

It supports `complex64` and its complex functions are significantly accelerated if you have an SSE2 or AVX2 chipset.  It is in alpha, however, and I don't believe `b.imag` would work at present although `imag(b)` would.

**Comment by itdaniher** [comment]
If by "some junk call" you mean "ipython," then yes. I'm seeing a much smaller performance win to the verbose implementation of `absolute` even with a much simpler test case, regardless of the order of the tests.

```
complex128 (500, 500)
verbose 2.4783826150014647
succinct 2.5618355290025647
```

```
complex128 (500, 500)
succinct 2.574124421000306
verbose 2.4413070990012784
```


The code I used is of the form:

```
import timeit
import numexpr as ne
import numpy as np

b = np.random.rand(500, 500) + 1j * np.random.rand(500, 500)

print(b.dtype, b.shape)
verbose_absolute = "ne.evaluate('(b.real**2 + b.imag**2)**0.5')"
succinct_absolute = "ne.evaluate('abs(b)')"

print('verbose', timeit.timeit(verbose_absolute, globals=globals(), number=100))
print('succinct', timeit.timeit(succinct_absolute, globals=globals(), number=100))
```

with the last two lines swapped.


I didn't bother running complex64, as the time consumed by an makes sense. I missed that part of the docs, mea culpa.

**Comment by itdaniher** [comment]
Running on my desktop (i7) has `succinct` consistently faster than `verbose` by roughly 50%. On ARM it's at best a tie. I'm not sure I entirely understand what's going on here, but it's likely yak shaving. 

On an unrelated note, is NEON SIMD acceleration on the roadmap? 

Thanks!

**Comment by itdaniher** [comment]
@robbmcleod I played around with numexpr3 for a spell, as complex64 operations are desirable, and found a number of reproducible ways of causing segfaults on x86 and ARM. If you're interested in taking a look, I can open up issues with test cases.

Regards!

**Comment by robbmcleod** [comment]
Hi, so it works in general like this on the first call to `ne.evaluate()`: 1.) if the function signature is not found in the cache dictionary, then it has to be parsed into an abstract syntax tree. This takes quite some time.  2.) Then the C-interpreter is called on the assembled bytecode, and if it has not been initiated previously it has to start up all its threads. This also takes time. So in order to get consistent benchmarks, a simple workaround is to run the test three times and take the minimum.  In this case the last two runs will always be faster. What I meant by 'junk call' is say, `ne.evaluate('b+b')` to initialize the C-interpreter. (Incidentally benchmarking NE2 and NE3 in the same Python interpreter is very tricky). 

NEON SIMD acceleration should work with NE3 out-of-the-box if auto-vectorization is enabled in your compiler.  I don't have one myself for testing. The difference between NE2 and NE3 here is that NE2 did pointer math, and put function calls inside loops, and unrolled the loops.  NE3 does array indexing and puts the loops inside the functions, so the compiler recognizes it and vectorizes it.  At some point hopefully Yeppp! (and Intel VML) will be added as backends, and Yeppp! is supposed to support NEON.

If you find problems with NE3 please feel free to raise an issue and I will add them to the test suite (which is the next task to do). Preface the issue with 'NE3:' please.  Strided array access for complex functions hasn't been implemented yet. I'm planning on raising issues on all the major roadmap items for NE3 soon but I'm travelling ATM.

**Comment by itdaniher** [comment]
Traveling too, but will add NE3 issues when I get a few moments.

Thanks for the mini-lesson on NE internals, very fascinating stuff!
