### ISSUE TITLE
Operators not defined in Expression

### ISSUE THREAD

**Issue by Uvar** [pydata/numexpr#294]
In expressions.py, class ExpressionNode:

line 451:
    if sys.version_info[0] < 3:
        __div__ = div_op
        __rdiv__ = binop('div', reversed=True)

All fine, but the operators are not defined for Python 3. Leading to unexpected behavior in conjunction with for instance the floor division operator `//`. Not that it is really necessary to define these particular __div__ and __rdiv__, but I guess I'd like it if support for floor division can be added. Right now, it will raise "Unsupported operand type(s) for //: 'VariableNode' and 'VariableNode' "

**Comment by robbmcleod** [comment]
`__floordiv__` is the dunder in the module `operations` so this isn't supported at all in NumExpr 2.6. After looking at it, I think the issue is somewhat more complicated than I would like because in C++ integer division is truncated, and in Python floor division is... floor division.  This is something that's intended to be in NumExpr 3.0 but it doesn't work properly right now so I'll mull it over and implement something.

**Comment by cod3monk** [comment]
If I were to be fine with a truncating integer division (since I only expect positive integers), would it be possible to access it?

**Comment by robbmcleod** [comment]
@cod3monk Not in the vanilla release `numexpr`, no.
