### ISSUE TITLE
Why in my case numexpr.evaluate() slower than eval()?

### ISSUE THREAD

**Issue by sun0727** [pydata/numexpr#301]
The purpose of using the numexpr.evaluate() is to speed up the compute. But im my case it wokrs even slower than numpy und eval(). I would like to know why?

code for test:
```python
import datetime
import numpy as np
import numexpr as ne

expr = '11808000.0*1j*x**2*exp(2.5e-10*1j*x) + 1512000.0*1j*x**2*exp(5.0e-10*1j*x)'


# use eval
start_eval = datetime.datetime.now()
namespace = dict(x=np.array([m+3j for m in range(1, 1001)]), exp=np.exp)
result_eval = eval(expr, namespace)
end_eval = datetime.datetime.now()
# print(result)
print("time by using eval   : %s" % (end_eval- start_eval))


# use numexpr
# ne.set_num_threads(8)
start_ne = datetime.datetime.now()
x = np.array([n+3j for n in range(1, 1001)])
result_ne = ne.evaluate(expr)
end_ne = datetime.datetime.now()
# print(result_ne)
print("time by using numexpr: %s" % (end_ne- start_ne))
```
return: 
time by using eval : ___0:00:00.002998
time by using numexpr: 0:00:00.052969

**Comment by gdementen** [comment]
Without looking precisely at your code, I suspect this is only because 
your arrays are too small. numexpr only provides some benefit on largish 
arrays. The reason is that there is some fixed cost to "compile" the 
expression, setup threads etc. which is only amortized for larger arrays.

Hope it helps,
Gaëtan

**Comment by robbmcleod** [comment]
As Gaëtan said, for NumExpr 2.6 you'll need arrays around 128 - 256 kElements to see a speed-up.  NumPy always starts faster as it doesn't have to synchronize at a thread barrier and otherwise spin-up the virtual machine 

Also, once you call `numexpr.evaluate()` the second time, it should be faster as it will have already compiled everything.  Compilation takes around 0.5 ms for simple expressions, more for longer expressions. The expression is stored as a hash, so the next time that computational expense is gone.

Also for timing I suggest `time.perf_counter()`.

**Comment by sun0727** [comment]
Thank you all for the answer and advice
