### ISSUE TITLE
"is", "in" operators are not documented

### ISSUE THREAD

**Issue by Dobatymo** [pydata/numexpr#321]
The python operators "is" and "in" are not documented explicitly and lead to unintuitive results.

```
>>> numexpr.evaluate("what is that")
array(False)
```

This is especially strange when other boolean operators (sometimes) throw exceptions.
```
1 or 2
```
is fine.
But
```
asd or qwe
```
```
TypeError: You can't use Python's standard boolean operators in NumExpr expressions. You should use their bitwise counterparts instead: '&' instead of 'and', '|' instead of 'or', and '~' instead of 'not'.
```

**Comment by robbmcleod** [comment]
Generally speaking NumExpr 2.6 does _not_ support logical operations. That you can trick it into using `is` is due to the fact that Python falls back on the `__eq__` dunder, which is supported. So it's really not like the Python `is` operator at all, in that it's checking equality and not whether one Python reference is occupying the same memory as the other reference.

`numexpr.evaluate('1 or 2')` works because they are constants, so NumExpr precomputes that in Python.

The fix here would be to implement `__is__` and `__in__` dunders to raise type errors.
