### ISSUE TITLE
nthreads cannot be larger than environment variable "NUMEXPR_MAX_THREADS" (64)

### ISSUE THREAD

**Issue by georgeha** [pydata/numexpr#322]
Hello, 
I am getting this error and I have no clue how to fix it.
Do you have any idea what is happening?
```
Error.  nthreads cannot be larger than environment variable "NUMEXPR_MAX_THREADS" (64)Error.  nthreads must be a positive integerError.
```

**Comment by robbmcleod** [comment]
We need a bit more information to help you.

What version of NumExpr are you using? Python? Operating system?

How many virtual cores does your machine have? 

Can you cut-and-paste the entire stack trace that the error generates?

Are any of the environment variables  `NUMEXPR_NUM_THREADS`, `NUMEXPR_MAX_THREADS`, or `OMP_NUM_THREADS` set?

**Comment by georgeha** [comment]
Hello,

I am using stampede2 : https://portal.tacc.utexas.edu/user-guides/stampede2
which has 68 KNL cores with 4 threads per core.
Python:  Python 2.7.15 |Anaconda, Inc.| 

OS
```
 uname -a
Linux login1.stampede2.tacc.utexas.edu 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

That is the only error I can see. I am not directly using NumExpr, I guess it is used by numpy?
Is that helpful?

**Comment by robbmcleod** [comment]
Yes NumExpr is a requirement of Pandas.

I assume you are using some bash submission script to queue a Python script?

Try inserting a line before you call the Python script

`set NUMEXPR_MAX_THREADS=68`

or if that doesn't work

`set NUMEXPR_MAX_THREADS=272`

**Comment by georgeha** [comment]
I tried both but it does not work.
If that helps this is the numexpr version that is installed:

```
>>> import numexpr
>>> numexpr.__version__
'2.6.8'
```

**Comment by robbmcleod** [comment]
Have you had any resolution to this?

I would suspect there's some confusion between environment variables. If you output `env` from the master node and paste that here I might be able to see what's happening.

**Comment by ssomnath** [comment]
I am experiencing the same problem as well. I am on an IBM Power 9 machine. I tried installing via pip / conda / source. I get the same error. 

When I built from source, I got a few warnings that were mentioned in another issue elsewhere:
``$ python setup.py build``
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building py_modules sources
building extension "numexpr.interpreter" sources
build_src: building npy-pkg config files
running build_py
copying build/src.linux-ppc64le-3.6/numexpr/__config__.py -> build/lib.linux-ppc64le-3.6/numexpr
Skipping optional fixer: buffer
Skipping optional fixer: idioms
Skipping optional fixer: set_literal
Skipping optional fixer: ws_comma
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize UnixCCompiler

``$ python setup.py install``
running install
running bdist_egg
running egg_info
running build_src
build_src
building py_modules sources
building extension "numexpr.interpreter" sources
build_src: building npy-pkg config files
writing numexpr.egg-info/PKG-INFO
writing dependency_links to numexpr.egg-info/dependency_links.txt
writing requirements to numexpr.egg-info/requires.txt
writing top-level names to numexpr.egg-info/top_level.txt
reading manifest file 'numexpr.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
**warning: no files found matching '*.cfg'
warning: no previously-included files found matching 'numexpr/__config__.py'
warning: no previously-included files found matching 'site.cfg'**
writing manifest file 'numexpr.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-ppc64le/egg
running install_lib
running build_py
copying build/src.linux-ppc64le-3.6/numexpr/__config__.py -> build/lib.linux-ppc64le-3.6/numexpr
Skipping optional fixer: buffer
Skipping optional fixer: idioms
Skipping optional fixer: set_literal
Skipping optional fixer: ws_comma
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
creating build/bdist.linux-ppc64le/egg
creating build/bdist.linux-ppc64le/egg/numexpr
creating build/bdist.linux-ppc64le/egg/numexpr/tests
copying build/lib.linux-ppc64le-3.6/numexpr/tests/__init__.py -> build/bdist.linux-ppc64le/egg/numexpr/tests
copying build/lib.linux-ppc64le-3.6/numexpr/tests/test_numexpr.py -> build/bdist.linux-ppc64le/egg/numexpr/tests
copying build/lib.linux-ppc64le-3.6/numexpr/__init__.py -> build/bdist.linux-ppc64le/egg/numexpr
copying build/lib.linux-ppc64le-3.6/numexpr/utils.py -> build/bdist.linux-ppc64le/egg/numexpr
copying build/lib.linux-ppc64le-3.6/numexpr/__config__.py -> build/bdist.linux-ppc64le/egg/numexpr
copying build/lib.linux-ppc64le-3.6/numexpr/cpuinfo.py -> build/bdist.linux-ppc64le/egg/numexpr
copying build/lib.linux-ppc64le-3.6/numexpr/version.py -> build/bdist.linux-ppc64le/egg/numexpr
copying build/lib.linux-ppc64le-3.6/numexpr/interpreter.cpython-36m-powerpc64le-linux-gnu.so -> build/bdist.linux-ppc64le/egg/numexpr
copying build/lib.linux-ppc64le-3.6/numexpr/necompiler.py -> build/bdist.linux-ppc64le/egg/numexpr
copying build/lib.linux-ppc64le-3.6/numexpr/expressions.py -> build/bdist.linux-ppc64le/egg/numexpr
byte-compiling build/bdist.linux-ppc64le/egg/numexpr/tests/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-ppc64le/egg/numexpr/tests/test_numexpr.py to test_numexpr.cpython-36.pyc
byte-compiling build/bdist.linux-ppc64le/egg/numexpr/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-ppc64le/egg/numexpr/utils.py to utils.cpython-36.pyc
byte-compiling build/bdist.linux-ppc64le/egg/numexpr/__config__.py to __config__.cpython-36.pyc
byte-compiling build/bdist.linux-ppc64le/egg/numexpr/cpuinfo.py to cpuinfo.cpython-36.pyc
byte-compiling build/bdist.linux-ppc64le/egg/numexpr/version.py to version.cpython-36.pyc
byte-compiling build/bdist.linux-ppc64le/egg/numexpr/necompiler.py to necompiler.cpython-36.pyc
byte-compiling build/bdist.linux-ppc64le/egg/numexpr/expressions.py to expressions.cpython-36.pyc
creating stub loader for numexpr/interpreter.cpython-36m-powerpc64le-linux-gnu.so
byte-compiling build/bdist.linux-ppc64le/egg/numexpr/interpreter.py to interpreter.cpython-36.pyc
creating build/bdist.linux-ppc64le/egg/EGG-INFO
copying numexpr.egg-info/PKG-INFO -> build/bdist.linux-ppc64le/egg/EGG-INFO
copying numexpr.egg-info/SOURCES.txt -> build/bdist.linux-ppc64le/egg/EGG-INFO
copying numexpr.egg-info/dependency_links.txt -> build/bdist.linux-ppc64le/egg/EGG-INFO
copying numexpr.egg-info/not-zip-safe -> build/bdist.linux-ppc64le/egg/EGG-INFO
copying numexpr.egg-info/requires.txt -> build/bdist.linux-ppc64le/egg/EGG-INFO
copying numexpr.egg-info/top_level.txt -> build/bdist.linux-ppc64le/egg/EGG-INFO
writing build/bdist.linux-ppc64le/egg/EGG-INFO/native_libs.txt
creating 'dist/numexpr-2.7.1-py3.6-linux-ppc64le.egg' and adding 'build/bdist.linux-ppc64le/egg' to it
removing 'build/bdist.linux-ppc64le/egg' (and everything under it)
Processing numexpr-2.7.1-py3.6-linux-ppc64le.egg
creating /gpfs/alpine/stf011/world-shared/mcclure/mcclure-conda-ben/lib/python3.6/site-packages/numexpr-2.7.1-py3.6-linux-ppc64le.egg
Extracting numexpr-2.7.1-py3.6-linux-ppc64le.egg to /gpfs/alpine/stf011/world-shared/mcclure/mcclure-conda-ben/lib/python3.6/site-packages
Adding numexpr 2.7.1 to easy-install.pth file

Installed /gpfs/alpine/stf011/world-shared/mcclure/mcclure-conda-ben/lib/python3.6/site-packages/numexpr-2.7.1-py3.6-linux-ppc64le.egg
Processing dependencies for numexpr==2.7.1
Searching for numpy==1.16.5
Best match: numpy 1.16.5
Adding numpy 1.16.5 to easy-install.pth file
Installing f2py script to /gpfs/alpine/world-shared/stf011/mcclure/mcclure-conda-ben/bin
Installing f2py3 script to /gpfs/alpine/world-shared/stf011/mcclure/mcclure-conda-ben/bin
Installing f2py3.6 script to /gpfs/alpine/world-shared/stf011/mcclure/mcclure-conda-ben/bin

Using /gpfs/alpine/stf011/world-shared/mcclure/mcclure-conda-ben/lib/python3.6/site-packages
Finished processing dependencies for numexpr==2.7.1
**Warning: Assuming default configuration (numexpr/tests/{setup_tests,setup}.py was not found)**



I even tried setting the environment variable before importing Numexpr (it doesn't seem to accept this value - see below). That did not help either. Also, Numexpr appears to be using far fewer threads than what is available on the machine. Here is what happens when I call ``test()``:

>>> os.environ["NUMEXPR_MAX_THREADS"]="272"
>>> import numexpr                
>>> numexpr.test()
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Numexpr version:   2.7.1
NumPy version:     1.16.5
Python version:    3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:18:58) 
[GCC 7.3.0]
Platform:          linux-ppc64le-#1 SMP Thu May 9 14:45:13 UTC 2019
CPU vendor:        
CPU model:         
CPU clock speed:    MHz
VML available?     False
Number of threads used by default: 16 (out of 128 detected cores)
Maximum number of threads: 68
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Error.  nthreads cannot be larger than environment variable "NUMEXPR_MAX_THREADS" (4).Traceback (most recent call last):
  File "<string>", line 4, in <module>
AssertionError
E......
======================================================================
ERROR: test_max_threads_unset (numexpr.tests.test_numexpr.test_threading_config)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gpfs/alpine/world-shared/stf011/mcclure/mcclure-conda-ben/lib/python3.6/site-packages/numexpr-2.7.1-py3.6-linux-ppc64le.egg/numexpr/tests/test_numexpr.py", line 970, in test_max_threads_unset
    subprocess.check_call([sys.executable, '-c', script])
  File "/gpfs/alpine/world-shared/stf011/mcclure/mcclure-conda-ben/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/gpfs/alpine/world-shared/stf011/mcclure/mcclure-conda-ben/bin/python', '-c', "import os\nif 'NUMEXPR_MAX_THREADS' in os.environ: os.environ.pop('NUMEXPR_MAX_THREADS')\nimport numexpr\nassert(numexpr.nthreads <= 8)\nexit(0)"]' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 5523 tests in 5.640s

FAILED (errors=1)
<unittest.runner.TextTestResult run=5523 errors=1 failures=0>


Any help here would be greatly appreciated. Thanks in advance

**Comment by robbmcleod** [comment]
Can you run instead the code fragment in that test so we can see which line fails?

    import os
    if 'NUMEXPR_MAX_THREADS' in os.environ: os.environ.pop('NUMEXPR_MAX_THREADS')
    import numexpr
    print('NumExpr.nthreads = ' + str(numexpr.nthreads))
    assert(numexpr.nthreads <= 8)
    exit(0)

I added the print statement.

**Comment by ssomnath** [comment]
Thank you for the prompt response. I ran your snippet. This is what I got:

``$ python``
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:18:58) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
``>>> import os``
``>>> if 'NUMEXPR_MAX_THREADS' in os.environ: os.environ.pop('NUMEXPR_MAX_THREADS')``
``>>> import numexpr``
``>>> print('NumExpr.nthreads = ' + str(numexpr.nthreads))``
NumExpr.nthreads = 16
``>>> assert(numexpr.nthreads <= 8)``
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
``>>> exit(0)``

**Comment by ssomnath** [comment]
Are the warnings I got during the build / install (highlighted in bold above and repeated below) a problem?

warning: no files found matching '*.cfg'
warning: no previously-included files found matching 'numexpr/config.py'
warning: no previously-included files found matching 'site.cfg'

Warning: Assuming default configuration (numexpr/tests/{setup_tests,setup}.py was not found)

**Comment by robbmcleod** [comment]
No the warnings are not an issue. If you want to compile with MKL support, you have to have a `site.cfg` file. You don't have one, so it's letting you know in a round-about way that it's compiling without MKL.

**Comment by ssomnath** [comment]
OK. Thank you for clarifying.

Yes that variable is indeed set:

``$ echo $OMP_NUM_THREADS``
16

**Comment by robbmcleod** [comment]
Ok, so I can change the test to also pop `OMP_NUM_THREADS`, but that error should not be cause for concern for you in day-to-day usage.

**Comment by ssomnath** [comment]
I see. I popped ``OMP_NUM_THREADS``. Now, I am able to run the tests. Details below:

$ python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:18:58) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> if 'OMP_NUM_THREADS' in os.environ: os.environ.pop('OMP_NUM_THREADS')
... 
'16'
>>> import numexpr
>>> print('NumExpr.nthreads = ' + str(numexpr.nthreads))
NumExpr.nthreads = 8
>>> assert(numexpr.nthreads <= 8)
>>> numexpr.test()
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Numexpr version:   2.7.1
NumPy version:     1.16.5
Python version:    3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:18:58) 
[GCC 7.3.0]
Platform:          linux-ppc64le-#1 SMP Thu May 9 14:45:13 UTC 2019
CPU vendor:        
CPU model:         
CPU clock speed:    MHz
VML available?     False
Number of threads used by default: 8 (out of 128 detected cores)
Maximum number of threads: 64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 5523 tests in 6.378s

OK
<unittest.runner.TextTestResult run=5523 errors=0 failures=0>
>>> exit()

**Comment by robbmcleod** [comment]
Ok, made a fix in https://github.com/pydata/numexpr/commit/d274455bc6a092cb49c0606f61a67c61afb86f72

I'll close this now as the original issue appears stale.

**Comment by zhong-yy** [comment]
I am experiencing the same problem now. The numexpr version is 2.10.2, pandas version is 2.2.2.

**Comment by Chrismarsh** [comment]
Also suddenly seeing this with numexpr 2.10.2. Not entirely sure what I changed in my env, but
```
import os; os.environ.pop('OMP_NUM_THREADS')
```
before importing numexpr (or before pandas and friends) is sufficient to resolve the detection issue (as per the PR) on numexpr on 2.10
