### ISSUE TITLE
Citation preferences

### ISSUE THREAD

**Issue by musoke** [pydata/numexpr#325]
How should this software be cited in academic journals?

If there isn't already a preference it is [easy to get a DOI](https://guides.github.com/activities/citable-code/).

**Comment by robbmcleod** [comment]
Is there any way to manually tell Zenodo to use the previous release as a target? It seems to demand that I make a new release in order to populate, which seems a little ridiculous.

**Comment by musoke** [comment]
You can just [upload a zip](https://zenodo.org/deposit).  I guess new releases will have DOIs assigned and grouped automatically.

**Comment by robbmcleod** [comment]
If I try and upload a tarball it asks me to provide a license, none of which are MIT.

**Comment by musoke** [comment]
Do you just see various Creative Commons suggestions?  I get "MIT License" suggested if I start typing it.

**Comment by robbmcleod** [comment]
Looks like a Javascript issue, in that I had security settings set such that the site wasn't very functional.

https://zenodo.org/record/1492916

Main problem I see at the moment is it doesn't give me a static link to the DOI badge. It's:

https://zenodo.org/record/1492916

So we are supposed to put this into our `README.rst`, but it's obviously going to change with each release? So when I upload to PyPI, it seems that I have to change the badge each time? Let's assume I'm going to forget to do that 100 % of the time, because releasing is already a lot of work. How can we automate the badge?

**Comment by musoke** [comment]
Fantastic,  I just added the citation to my drafts.

@bashtage is right that the future releases should sort themselves out more nicely.

**Comment by robbmcleod** [comment]
OK, good to know that things are workable for the moment.

I'll leave this issue open until 2.6.9, which hopefully should not be too long. I'm not sure I'll be able to get the correct badge on PyPI, but it should be ok here.

**Comment by robbmcleod** [comment]
Ok, the Zenodo hook appears to be turned on.  I'll update the badge for  the Github readme but the PyPi badge will remain behind, unfortunately. In retrospect since Zenodo is working off git tags this could have been avoided by setting it up before uploading to PyPi.

Anyway, closing.
