### ISSUE TITLE
Error in dtype of calculated array

### ISSUE THREAD

**Issue by rhstanton** [pydata/numexpr#332]
Using numexpr 2.6.9, I'm getting results that seem to be of type np.int64, but aren't quite, causing trouble, for example, with isinstance(). Here's some sample code showing the problem:

---------

import numpy as np
import numexpr as ne

a = np.array([1, 1])
b = ne.evaluate("a * 2")

type_a = type(a[0])
type_b = type(b[0])

print("Type of a is ", type_a)
print("Type of b is ", type_b)
print("Are these the same type?", type_a == type_b)
print("Is a of type np.int64?", isinstance(a[0], np.int64))
print("Is b of type np.int64?", isinstance(b[0], np.int64))

----------

And here's the corresponding output. What type _is_ array b?

Type of a is  <class 'numpy.int64'>
Type of b is  <class 'numpy.int64'>
Are these the same type? False
Is a of type np.int64? True
Is b of type np.int64? False

**Comment by robbmcleod** [comment]
The way to check types on NumPy arrays is to check the `.dtype` attribute:

    import numpy as np
    import numexpr as ne

    a = np.array([1, 1])
    b = ne.evaluate("a * 2")
    c = a * 2

    dtype_a = a.dtype
    dtype_b = b.dtype
    dtype_c = c.dtype

    print("dtype of a is ", dtype_a)
    print("dtype of b is ", dtype_b)
    print("dtype of c is ", dtype_c)
    print("Are a and b by the same dtype?", dtype_a == dtype_b)
    print("Are b and c by the same dtype?", dtype_b == dtype_c)
    print("Is a of dtype np.int32?", isinstance(a[0].dtype, np.int32))
    print("Is b of dtype np.int32?", isinstance(b[0].dtype, np.int32))
    print("Is c of dtype np.int32?", isinstance(c[0].dtype, np.int32))

So you can see, checking for equivalence of `a.dtype == b.dtype` works as desired. What you are running into here is confusion over the relationship between NumPy scalars and ndarrays. NumPy has a bunch of implementions in `__eq__` for dtypes so that you can match them to scalars and/or string representations. But the underlying objects of a singleton scalar compared to a single index of a NumPy array. are actually different.

**Comment by rhstanton** [comment]
I do see that a.dtype == b.dtype. So is using a.dtype better than using type(a[0])? In this example, What is the difference between type(a[0]) and type(b[0])? They both look the same (and aren't both a[0] and b[0] scalars?), but fail an equality test.

In the last three lines of your code above, do you really want to have a[0].dtype as the first argument of isinstance, rather than just a[0]? If I get rid of the .dtype in those three statements (and switch to np.int64), I get False for the second statement and True for the first and third. Still seems odd...

**Comment by robbmcleod** [comment]
> So is using a.dtype better than using type(a[0])?

Yes.

>In this example, what is the difference between type(a[0]) and type(b[0])? 

NumExpr 2.6 redefines some types internally because it doesn't support the full range of dtypes, due to a limited number of bytecodes.

> In the last three lines of your code above, do you really want to have a[0].dtype as the first argument of isinstance, rather than just a[0]?

It's not really relevant, the way to do a comparison here is `a.dtype == b.dtype`. I am more-so showing that using `isinstance` gives erroneous results. It would surely be better if NumPy didn't have these gotchas between scalars and vector elements, but it does, and knowing what I do of the NumPy internals, it's just something we all have to live with.

Anyway, closing, as really not a NumExpr issue in my opinion.
