### ISSUE TITLE
Parameter tuning for maximizing performance

### ISSUE THREAD

**Issue by ssomnath** [pydata/numexpr#366]
Hello, I am trying to find out how I can get the best performance out of numexpr. For the sake of simplicity, I am using the [examples on the documentation](https://numexpr.readthedocs.io/projects/NumExpr3/en/latest/intro.html#expected-performance) in [this script](https://github.com/JamesEMcClure/TomographyWorkflow/blob/tomopy_build/numexpr_vs_numpy.py). I am using a single IBM Power9 CPU and numexpr version 2.7.1. 

I have tried changing the number of threads used using ``ne.set_num_threads(n_threads)`` for array sizes of [1E+6](https://github.com/JamesEMcClure/TomographyWorkflow/blob/tomopy_build/numexpr_vs_threads_1E6.png) and [1E+7](https://github.com/JamesEMcClure/TomographyWorkflow/blob/tomopy_build/numexpr_vs_threads_1E7.png). I have provided links to the plots. 

I have also tried just picking one expression and varying the ``OMP_NUM_THREADS`` argument to see if numexpr performance improves. Here are the plots for the [1E+6](https://github.com/JamesEMcClure/TomographyWorkflow/blob/tomopy_build/numexpr_omp_num_threads_1E6.png) and [1E+7](https://github.com/JamesEMcClure/TomographyWorkflow/blob/tomopy_build/numexpr_omp_num_threads_1E7.png) array sizes. The latter shows clearer trends. Regardless, I only see very minor improvements in performance when I vary the ``OMP_NUM_THREADS`` environment variable. Note that I do get the following warning:
```bash
Warning: OMP_NUM_THREADS=16 is greater than available PU's
```

Is this normal performance? How do I configure things so I maximize performance? Any help / guidance is greatly appreciated

**Comment by robbmcleod** [comment]
I have no experience with a Power9 CPU, but generally speaking you are not going to get very good thread scaling past eight threads on x64 CPUs. Four threads per process is generally the sweet spot. If you want to use `numexpr` in a cluster-environment, then likely you should consider investigating a hybrid multi-process, multi-thread approach. E.g. if you have a 32-core system, you might run 8 processes, each with 4 threads. You will have to balance memory consumption and IO bottleneck as well (which generally biases towards fewer processes).

Note that I've not seen `numexpr` or similar tools benefit much from using virtual cores in a hyperthreading CPU. So if you only have 32-physical cores but 64-virtual, I doubt you will see a benefit from scaling to use all those virtual cores.

If you really want to run a lot of threads, I would consider increasing the `BLOCKSIZE1` macro and re-compling so that each block is larger and hence has less overhead associated with it. `BLOCKSIZE1` cannot be increased indefinitely as you will start to run out of L2 cache at some point.

If you really need increased performance, `numexpr3` will be about twice as fast as `numexpr` 2.7 and (last I checked) `numba`. `numexpr3` makes use of AVX2 vectorized instructions when available. However, please note I do not recommend `numexpr3` for public open-source situations, it should really only be used in private code bases, as it is not stable.

Lastly for your tests, you need to do a dry run for every expression first before you do your benchmark. There will be start-up times in interpreting the expressions.

**Comment by ssomnath** [comment]
I see. This makes sense. Thank you. I will try out the things you suggested

**Comment by robbmcleod** [comment]
I think I'll close this one as the original issue seems to be resolved.
