### ISSUE TITLE
Why is Pandas importing NumExpr? 

### ISSUE THREAD

**Issue by masterholdy** [pydata/numexpr#382]
Hi Guys,

i just added Pandas to my Project and now im getting these logs 247:

```python
[2021-09-22 19:51:18,211] {utils.py:145} INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2021-09-22 19:51:18,211] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
```
Im only using pandas twice like this
```python
df = pd.DataFrame(img_infos)
describe = df.describe()
```

Im not using any kind of Multiprocessing *with* Pandas. Why am i getting these kind of messages out of the blue? Im using ` from multiprocessing import Pool ` For Multiprocessing - but i havent gotten any message like theese before importing pandas.

Ty in advanced

**Comment by robbmcleod** [comment]
This would be a question for the `pandas` people. We're trying to be explicit about things (such as these environment variables) because we've had issues in the past. It's easy enough to suppress these messages if you don't want to see them, by changing the logging level before the import and then restoring it. Or just by pro-actively setting the "NUMEXPR_MAX_THREADS" environment variable, which may be done with `os.environ()`.

`numexpr` has nothing to do with multiprocessing; it's a multi-threaded virtual machine that designed to accelerate `numpy` calculations. Pandas uses it in their backend in some places.

**Comment by robbmcleod** [comment]
Closing.
