### ISSUE TITLE
Unexpected result of logical operators

### ISSUE THREAD

**Issue by jonas-eschle** [pydata/numexpr#408]
Hi all, first of all, thanks a lot for this amazing library, using it on a daily basis!

I've encountered recently a few surprising results when updating an old frameworks unittests using logical operators. Three operators, examples:

Namely, the following returns 7 whereas I would expect it to return True or 1
```
import numexpr
numexpr.evaluate('3 | 5')  # -> array(7, dtype=int32)
```
or 
```
numexpr.evaluate('~1')  # -> array(2, dtype=int32)
```
where I would expect 0 (logical False)

Same for the xor `^` operator.

Is this a bug or a feature? If it is a feature, I have not found any docs covering it.

Version numexpr: 2.8.0
Python: 3.10

**Comment by robbmcleod** [comment]
The `|` operator is bitwise, as is `&`, as is `~`, as is `^`. I agree that the documentation under "Supported Operators" claims they are logical operators. I'll fix the documentation. I'll point out in all cases you've cited NumExpr matches default Python behavior, which is the goal here.

**Comment by jonas-eschle** [comment]
Hm, are you sure that this is the expected behavior? The [changelog of 2.1](https://numexpr.readthedocs.io/projects/NumExpr3/en/latest/release_notes.html#changes-from-2-0-1-to-2-1) suggests the opposite:
>  Now, when trying to use pure Python boolean operators, ‘and’, ‘or’ and ‘not’, an error is issued suggesting that ‘&’, ‘|’ and ‘~’ should be used instead (fixes #24).

Are you suggesting that the behavior is changing, breaking backwards compatibility? Won't this screw up all the code of any downstream library, say pandas, is this intended?

Or am I missing something here?

**Comment by robbmcleod** [comment]
Ok I am wrong there are not bitwise operations in NE2.8, I was thinking of NE3. This is the code for boolean operations in NumExpr:

        /* Bool */
        case OP_INVERT_BB: VEC_ARG1(b_dest = !b1);
        case OP_AND_BBB: VEC_ARG2(b_dest = (b1 && b2));
        case OP_OR_BBB: VEC_ARG2(b_dest = (b1 || b2));

        case OP_EQ_BBB: VEC_ARG2(b_dest = (b1 == b2));
        case OP_NE_BBB: VEC_ARG2(b_dest = (b1 != b2));
        case OP_WHERE_BBBB: VEC_ARG3(b_dest = b1 ? b2 : b3);

So for logical operations to work correctly, the data types pass in need to be `np.bool`. What's happening here is that since you have just literals, those literals are being evaluated when NumExpr parses the expression rather than going to to the virtual machine. So Python is evaluating the expression, not NumExpr. E.g. if you pass in variables with integer values it will not work:

    a = 1
    ne.evalute('~a')

errors because there is no such operation:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Sync\soft\numexpr\numexpr\necompiler.py", line 822, in evaluate
    compiled_ex = _numexpr_cache[numexpr_key] = NumExpr(ex, signature, **context)
  File "C:\Sync\soft\numexpr\numexpr\necompiler.py", line 621, in NumExpr
    threeAddrProgram, inputsig, tempsig, constants, input_names = precompile(ex, signature, context)
  File "C:\Sync\soft\numexpr\numexpr\necompiler.py", line 566, in precompile
    ast = typeCompileAst(ast)
  File "C:\Sync\soft\numexpr\numexpr\necompiler.py", line 202, in typeCompileAst
    raise NotImplementedError(
NotImplementedError: couldn't find matching opcode for 'invert_ii'
```

**Comment by jonas-eschle** [comment]
Okay, I also see the changes in the docs, but it all confuses me more tbh. Is NE3 gonna be out soon, or already on develop to try out?
To put things differently: how to
- use "xor int"?
- use "not int"? is it fine like that?

How are logical operators used now? The docs basically removed them.

**Comment by robbmcleod** [comment]
You can only do logical boolean operations in NumExpr 2.8 on boolean dtype. So either the input arrays have to be boolean, or you have to do some operation (like `<`) that outputs boolean. 

NumExpr3 I wouldn't use in production code, but you can certainly get it from pypi if you want to use it for scripting tasks. It will probably never be 'released' in any official sense simply due to time constraints.

**Comment by jonas-eschle** [comment]
Okay, so there also no way to explicitly cast, is that correct?

Thanks a lot for the answers and the great library!

**Comment by robbmcleod** [comment]
No, there are casting functions in the C++ virtual machine, but there isn't any way built into the Python interface to access them. 

NE3 does have explicit casts.

**Comment by robbmcleod** [comment]
@jonas-eschle may we close this one?

**Comment by jonas-eschle** [comment]
I guess so, really looking forward to NE3
