### ISSUE TITLE
OMP_NUM_THREADS with list of ints throws ValueError: invalid literal for int()

### ISSUE THREAD

**Issue by christianversloot** [pydata/numexpr#421]
We are using `numexpr` quite often, thanks for all the work!

In our base container, by default, we set `OMP_NUM_THREADS` to a value that reduces the number of `parallel` threads.
In the default setting, we have it set to `'4,3,2'`, which seems to be a correct value per the OpenMP docs: 

> The value of this environment variable must be a list of positive integer values.
https://www.openmp.org/spec-html/5.0/openmpse50.html
https://www.openmp.org/wp-content/uploads/OpenMP-API-Specification-5-2.pdf

Numexpr throws this obvious error as the string is invalid when converting it to an `int`:

```
6-10-2022 08:49:15  File "/usr/local/lib/python3.9/site-packages/numexpr/utils.py", line 156, in _init_num_threads
6-10-2022 08:49:15    requested_threads = int(os.environ['OMP_NUM_THREADS'])
6-10-2022 08:49:15ValueError: invalid literal for int() with base 10: '4,3,2'
```

I was wondering if the Numexpr assumption that this envvar must always be an int string can be changed into either an int or a comma-separated list of ints (which string-wise, can be the same thing when e.g. splitting using commas). This way, it supports the options specified by OpenMP docs.

Looking forward to hearing from you - thanks! :)

**Comment by FrancescAlted** [comment]
We support only int values for `OMP_NUM_THREADS` env variable.  The reason is that numexpr does not use OpenMP internally, but rather plain threads, which are less featured.  Normally numexpr uses the `NUMEXPR_MAX_THREADS` variable for setting this, but we are honoring the integer version of `OMP_NUM_THREADS` just for convenience.

**Comment by robbmcleod** [comment]
As @FrancescAlted says you should use `NUMEXPR_MAX_THREADS`  and `NUMEXPR_NUM_THREADS`. If `NUMEXPR_NUM_THREADS` is set, any value you set to `OMP_NUM_THREADS` will be ignored by NumExpr on import. E.g. the following should work:

```
set NUMEXPR_NUM_THREADS = 24
set OMP_NUM_THREADS=2,3,4
```

`OMP_NUM_THREADS` support is really a legacy issue. Since this is a 'will not fix', I'll close but feel free to re-open the issue if you feel there's additional issues.
