### ISSUE TITLE
Bitwise AND not working with variable

### ISSUE THREAD

**Issue by if-mar** [pydata/numexpr#425]
I'm using python 3.8.10 with numexpr 2.8.4 and want to evaluate an expression containing a bitwise AND.

But the following code fails with `NotImplementedError: couldn't find matching opcode for 'and_bli'`

```
import numexpr as ne
r = ne.evaluate('(a&2)', {'a': 11})  # FAILS with NotImplementedError: couldn't find matching opcode for 'and_bli'
print(r)
```

But when I eliminate the variable, it works as expected:

```
import numexpr as ne
r = ne.evaluate('(11&2)')
print(r)  # prints 2
```

What do I need to change to make above code working?

**Comment by 27rabbitlt** [comment]
I'm also new here but I think I can answer this question.

Unfortunately, numexpr doesn't support bitwise AND for two integers. As we can see in the opcode.hpp, the only operation related to bitwise AND is "and_bbb" which means that this operation is only for two boolean variables.

The reason why the latter code `ne.evaluate("11&2") works is that, after necompiler, this statement has been compiled to a constant. If you print the three-address-code, you can see this:

![image](https://user-images.githubusercontent.com/116789663/202399631-02e77d91-8463-426a-b299-670986cd21cb.png)

This means that the true code numexpr executes is actually a copy from constant 2 (which is calculated by ne-compiler, instead of Virtual Machine of numexpr) to the result variable `r`.

**Comment by robbmcleod** [comment]
@if-mar, sorry for the delay in replying, I thought I had already. Bitwise operations are not supported in NumExpr:

https://numexpr.readthedocs.io/projects/NumExpr3/en/latest/user_guide.html#supported-operators

The `&` operator in NumExpr 2.8 is in-fact a `logical_and` and it only works on `bool` dtype. I get confused myself about this one fairly often, but it's the way it's been for many years

@27rabbitlt not quite, when you have just constants in an expression NumExpr 2.8 will short-circuit the calculation and do it entirely in Python, bypassing the virtual machine. This leads to a lot of 'gotcha' cases, like this one, unfortunately.
